// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: black_site.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countDetaineesByStatus = `-- name: CountDetaineesByStatus :many
SELECT status, COUNT(*) as count
FROM black_site_detainees
GROUP BY status
ORDER BY status
`

type CountDetaineesByStatusRow struct {
	Status string `db:"status" json:"status"`
	Count  int64  `db:"count" json:"count"`
}

func (q *Queries) CountDetaineesByStatus(ctx context.Context) ([]CountDetaineesByStatusRow, error) {
	rows, err := q.db.Query(ctx, countDetaineesByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountDetaineesByStatusRow{}
	for rows.Next() {
		var i CountDetaineesByStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countDetaineesByThreatLevel = `-- name: CountDetaineesByThreatLevel :many
SELECT threat_level, COUNT(*) as count
FROM black_site_detainees
GROUP BY threat_level
ORDER BY
    CASE threat_level
        WHEN 'APT' THEN 1
        WHEN 'ZERO-DAY' THEN 2
        WHEN 'EXPLOIT' THEN 3
        WHEN 'CVE' THEN 4
        WHEN 'IOC' THEN 5
    END
`

type CountDetaineesByThreatLevelRow struct {
	ThreatLevel string `db:"threat_level" json:"threat_level"`
	Count       int64  `db:"count" json:"count"`
}

func (q *Queries) CountDetaineesByThreatLevel(ctx context.Context) ([]CountDetaineesByThreatLevelRow, error) {
	rows, err := q.db.Query(ctx, countDetaineesByThreatLevel)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountDetaineesByThreatLevelRow{}
	for rows.Next() {
		var i CountDetaineesByThreatLevelRow
		if err := rows.Scan(&i.ThreatLevel, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countDetaineesTotal = `-- name: CountDetaineesTotal :one
SELECT COUNT(*) as count FROM black_site_detainees
`

func (q *Queries) CountDetaineesTotal(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countDetaineesTotal)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDetainee = `-- name: CreateDetainee :one
INSERT INTO black_site_detainees (
    bsi_id, sha_hash, title, threat_level, status,
    captured_by, file_references, interrogation_notes,
    witness_statement, damage_assessment, recommended_remedy
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
) RETURNING id, bsi_id, sha_hash, title, threat_level, status, captured_by, file_references, interrogation_notes, witness_statement, damage_assessment, recommended_remedy, created_at, updated_at
`

type CreateDetaineeParams struct {
	BsiID              string `db:"bsi_id" json:"bsi_id"`
	ShaHash            string `db:"sha_hash" json:"sha_hash"`
	Title              string `db:"title" json:"title"`
	ThreatLevel        string `db:"threat_level" json:"threat_level"`
	Status             string `db:"status" json:"status"`
	CapturedBy         string `db:"captured_by" json:"captured_by"`
	FileReferences     string `db:"file_references" json:"file_references"`
	InterrogationNotes string `db:"interrogation_notes" json:"interrogation_notes"`
	WitnessStatement   string `db:"witness_statement" json:"witness_statement"`
	DamageAssessment   string `db:"damage_assessment" json:"damage_assessment"`
	RecommendedRemedy  string `db:"recommended_remedy" json:"recommended_remedy"`
}

func (q *Queries) CreateDetainee(ctx context.Context, arg CreateDetaineeParams) (BlackSiteDetainee, error) {
	row := q.db.QueryRow(ctx, createDetainee,
		arg.BsiID,
		arg.ShaHash,
		arg.Title,
		arg.ThreatLevel,
		arg.Status,
		arg.CapturedBy,
		arg.FileReferences,
		arg.InterrogationNotes,
		arg.WitnessStatement,
		arg.DamageAssessment,
		arg.RecommendedRemedy,
	)
	var i BlackSiteDetainee
	err := row.Scan(
		&i.ID,
		&i.BsiID,
		&i.ShaHash,
		&i.Title,
		&i.ThreatLevel,
		&i.Status,
		&i.CapturedBy,
		&i.FileReferences,
		&i.InterrogationNotes,
		&i.WitnessStatement,
		&i.DamageAssessment,
		&i.RecommendedRemedy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRendition = `-- name: CreateRendition :one
INSERT INTO black_site_renditions (
    detainee_id, commit_hash, rendered_by, method, notes
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, detainee_id, rendered_at, commit_hash, rendered_by, method, notes, created_at
`

type CreateRenditionParams struct {
	DetaineeID int32  `db:"detainee_id" json:"detainee_id"`
	CommitHash string `db:"commit_hash" json:"commit_hash"`
	RenderedBy string `db:"rendered_by" json:"rendered_by"`
	Method     string `db:"method" json:"method"`
	Notes      string `db:"notes" json:"notes"`
}

func (q *Queries) CreateRendition(ctx context.Context, arg CreateRenditionParams) (BlackSiteRendition, error) {
	row := q.db.QueryRow(ctx, createRendition,
		arg.DetaineeID,
		arg.CommitHash,
		arg.RenderedBy,
		arg.Method,
		arg.Notes,
	)
	var i BlackSiteRendition
	err := row.Scan(
		&i.ID,
		&i.DetaineeID,
		&i.RenderedAt,
		&i.CommitHash,
		&i.RenderedBy,
		&i.Method,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const getDetainee = `-- name: GetDetainee :one
SELECT id, bsi_id, sha_hash, title, threat_level, status, captured_by, file_references, interrogation_notes, witness_statement, damage_assessment, recommended_remedy, created_at, updated_at FROM black_site_detainees
WHERE bsi_id = $1
`

func (q *Queries) GetDetainee(ctx context.Context, bsiID string) (BlackSiteDetainee, error) {
	row := q.db.QueryRow(ctx, getDetainee, bsiID)
	var i BlackSiteDetainee
	err := row.Scan(
		&i.ID,
		&i.BsiID,
		&i.ShaHash,
		&i.Title,
		&i.ThreatLevel,
		&i.Status,
		&i.CapturedBy,
		&i.FileReferences,
		&i.InterrogationNotes,
		&i.WitnessStatement,
		&i.DamageAssessment,
		&i.RecommendedRemedy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDetaineeByID = `-- name: GetDetaineeByID :one
SELECT id, bsi_id, sha_hash, title, threat_level, status, captured_by, file_references, interrogation_notes, witness_statement, damage_assessment, recommended_remedy, created_at, updated_at FROM black_site_detainees
WHERE id = $1
`

func (q *Queries) GetDetaineeByID(ctx context.Context, id int32) (BlackSiteDetainee, error) {
	row := q.db.QueryRow(ctx, getDetaineeByID, id)
	var i BlackSiteDetainee
	err := row.Scan(
		&i.ID,
		&i.BsiID,
		&i.ShaHash,
		&i.Title,
		&i.ThreatLevel,
		&i.Status,
		&i.CapturedBy,
		&i.FileReferences,
		&i.InterrogationNotes,
		&i.WitnessStatement,
		&i.DamageAssessment,
		&i.RecommendedRemedy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDetainees = `-- name: ListDetainees :many
SELECT id, bsi_id, sha_hash, title, threat_level, status, captured_by, file_references, interrogation_notes, witness_statement, damage_assessment, recommended_remedy, created_at, updated_at FROM black_site_detainees
ORDER BY
    CASE threat_level
        WHEN 'APT' THEN 1
        WHEN 'ZERO-DAY' THEN 2
        WHEN 'EXPLOIT' THEN 3
        WHEN 'CVE' THEN 4
        WHEN 'IOC' THEN 5
    END,
    bsi_id
`

func (q *Queries) ListDetainees(ctx context.Context) ([]BlackSiteDetainee, error) {
	rows, err := q.db.Query(ctx, listDetainees)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BlackSiteDetainee{}
	for rows.Next() {
		var i BlackSiteDetainee
		if err := rows.Scan(
			&i.ID,
			&i.BsiID,
			&i.ShaHash,
			&i.Title,
			&i.ThreatLevel,
			&i.Status,
			&i.CapturedBy,
			&i.FileReferences,
			&i.InterrogationNotes,
			&i.WitnessStatement,
			&i.DamageAssessment,
			&i.RecommendedRemedy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDetaineesByThreatLevel = `-- name: ListDetaineesByThreatLevel :many
SELECT id, bsi_id, sha_hash, title, threat_level, status, captured_by, file_references, interrogation_notes, witness_statement, damage_assessment, recommended_remedy, created_at, updated_at FROM black_site_detainees
WHERE threat_level = $1
ORDER BY bsi_id
`

func (q *Queries) ListDetaineesByThreatLevel(ctx context.Context, threatLevel string) ([]BlackSiteDetainee, error) {
	rows, err := q.db.Query(ctx, listDetaineesByThreatLevel, threatLevel)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BlackSiteDetainee{}
	for rows.Next() {
		var i BlackSiteDetainee
		if err := rows.Scan(
			&i.ID,
			&i.BsiID,
			&i.ShaHash,
			&i.Title,
			&i.ThreatLevel,
			&i.Status,
			&i.CapturedBy,
			&i.FileReferences,
			&i.InterrogationNotes,
			&i.WitnessStatement,
			&i.DamageAssessment,
			&i.RecommendedRemedy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRenditions = `-- name: ListRenditions :many
SELECT r.id, r.detainee_id, r.rendered_at, r.commit_hash, r.rendered_by, r.method, r.notes, r.created_at, d.bsi_id, d.sha_hash, d.title, d.threat_level
FROM black_site_renditions r
JOIN black_site_detainees d ON d.id = r.detainee_id
ORDER BY r.rendered_at DESC
`

type ListRenditionsRow struct {
	ID          int32            `db:"id" json:"id"`
	DetaineeID  int32            `db:"detainee_id" json:"detainee_id"`
	RenderedAt  pgtype.Timestamp `db:"rendered_at" json:"rendered_at"`
	CommitHash  string           `db:"commit_hash" json:"commit_hash"`
	RenderedBy  string           `db:"rendered_by" json:"rendered_by"`
	Method      string           `db:"method" json:"method"`
	Notes       string           `db:"notes" json:"notes"`
	CreatedAt   pgtype.Timestamp `db:"created_at" json:"created_at"`
	BsiID       string           `db:"bsi_id" json:"bsi_id"`
	ShaHash     string           `db:"sha_hash" json:"sha_hash"`
	Title       string           `db:"title" json:"title"`
	ThreatLevel string           `db:"threat_level" json:"threat_level"`
}

func (q *Queries) ListRenditions(ctx context.Context) ([]ListRenditionsRow, error) {
	rows, err := q.db.Query(ctx, listRenditions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRenditionsRow{}
	for rows.Next() {
		var i ListRenditionsRow
		if err := rows.Scan(
			&i.ID,
			&i.DetaineeID,
			&i.RenderedAt,
			&i.CommitHash,
			&i.RenderedBy,
			&i.Method,
			&i.Notes,
			&i.CreatedAt,
			&i.BsiID,
			&i.ShaHash,
			&i.Title,
			&i.ThreatLevel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRenditionsForDetainee = `-- name: ListRenditionsForDetainee :many
SELECT id, detainee_id, rendered_at, commit_hash, rendered_by, method, notes, created_at FROM black_site_renditions
WHERE detainee_id = $1
ORDER BY rendered_at DESC
`

func (q *Queries) ListRenditionsForDetainee(ctx context.Context, detaineeID int32) ([]BlackSiteRendition, error) {
	rows, err := q.db.Query(ctx, listRenditionsForDetainee, detaineeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BlackSiteRendition{}
	for rows.Next() {
		var i BlackSiteRendition
		if err := rows.Scan(
			&i.ID,
			&i.DetaineeID,
			&i.RenderedAt,
			&i.CommitHash,
			&i.RenderedBy,
			&i.Method,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDetaineeStatus = `-- name: UpdateDetaineeStatus :exec
UPDATE black_site_detainees
SET status = $2, updated_at = NOW()
WHERE bsi_id = $1
`

type UpdateDetaineeStatusParams struct {
	BsiID  string `db:"bsi_id" json:"bsi_id"`
	Status string `db:"status" json:"status"`
}

func (q *Queries) UpdateDetaineeStatus(ctx context.Context, arg UpdateDetaineeStatusParams) error {
	_, err := q.db.Exec(ctx, updateDetaineeStatus, arg.BsiID, arg.Status)
	return err
}
