// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: ct_cache.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCTCache = `-- name: GetCTCache :one
SELECT domain, subdomains, unique_count, source, fetched_at, expires_at
FROM ct_subdomain_cache
WHERE domain = $1 AND expires_at > NOW()
`

func (q *Queries) GetCTCache(ctx context.Context, domain string) (CtSubdomainCache, error) {
	row := q.db.QueryRow(ctx, getCTCache, domain)
	var i CtSubdomainCache
	err := row.Scan(
		&i.Domain,
		&i.Subdomains,
		&i.UniqueCount,
		&i.Source,
		&i.FetchedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getSTBudget = `-- name: GetSTBudget :one
SELECT month_key, calls_used, domains_enriched, last_called_at
FROM securitytrails_budget
WHERE month_key = $1
`

type GetSTBudgetRow struct {
	MonthKey        string           `db:"month_key" json:"month_key"`
	CallsUsed       int32            `db:"calls_used" json:"calls_used"`
	DomainsEnriched []byte           `db:"domains_enriched" json:"domains_enriched"`
	LastCalledAt    pgtype.Timestamp `db:"last_called_at" json:"last_called_at"`
}

func (q *Queries) GetSTBudget(ctx context.Context, monthKey string) (GetSTBudgetRow, error) {
	row := q.db.QueryRow(ctx, getSTBudget, monthKey)
	var i GetSTBudgetRow
	err := row.Scan(
		&i.MonthKey,
		&i.CallsUsed,
		&i.DomainsEnriched,
		&i.LastCalledAt,
	)
	return i, err
}

const getTopAnalyzedDomains = `-- name: GetTopAnalyzedDomains :many
SELECT domain, COUNT(*) AS analysis_count
FROM domain_analyses
WHERE analysis_success = TRUE
  AND created_at > NOW() - INTERVAL '30 days'
GROUP BY domain
ORDER BY analysis_count DESC
LIMIT $1
`

type GetTopAnalyzedDomainsRow struct {
	Domain        string `db:"domain" json:"domain"`
	AnalysisCount int64  `db:"analysis_count" json:"analysis_count"`
}

func (q *Queries) GetTopAnalyzedDomains(ctx context.Context, limit int32) ([]GetTopAnalyzedDomainsRow, error) {
	rows, err := q.db.Query(ctx, getTopAnalyzedDomains, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTopAnalyzedDomainsRow{}
	for rows.Next() {
		var i GetTopAnalyzedDomainsRow
		if err := rows.Scan(&i.Domain, &i.AnalysisCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeCTCacheExpired = `-- name: PurgeCTCacheExpired :exec
DELETE FROM ct_subdomain_cache WHERE expires_at < NOW()
`

func (q *Queries) PurgeCTCacheExpired(ctx context.Context) error {
	_, err := q.db.Exec(ctx, purgeCTCacheExpired)
	return err
}

const upsertCTCache = `-- name: UpsertCTCache :exec
INSERT INTO ct_subdomain_cache (domain, subdomains, unique_count, source, fetched_at, expires_at)
VALUES ($1, $2, $3, $4, NOW(), NOW() + INTERVAL '24 hours')
ON CONFLICT (domain) DO UPDATE SET
    subdomains = EXCLUDED.subdomains,
    unique_count = EXCLUDED.unique_count,
    source = EXCLUDED.source,
    fetched_at = NOW(),
    expires_at = NOW() + INTERVAL '24 hours'
`

type UpsertCTCacheParams struct {
	Domain      string `db:"domain" json:"domain"`
	Subdomains  []byte `db:"subdomains" json:"subdomains"`
	UniqueCount int32  `db:"unique_count" json:"unique_count"`
	Source      string `db:"source" json:"source"`
}

func (q *Queries) UpsertCTCache(ctx context.Context, arg UpsertCTCacheParams) error {
	_, err := q.db.Exec(ctx, upsertCTCache,
		arg.Domain,
		arg.Subdomains,
		arg.UniqueCount,
		arg.Source,
	)
	return err
}

const upsertSTBudget = `-- name: UpsertSTBudget :exec
INSERT INTO securitytrails_budget (month_key, calls_used, domains_enriched, last_called_at, updated_at)
VALUES ($1, $2, $3, NOW(), NOW())
ON CONFLICT (month_key) DO UPDATE SET
    calls_used = EXCLUDED.calls_used,
    domains_enriched = EXCLUDED.domains_enriched,
    last_called_at = NOW(),
    updated_at = NOW()
`

type UpsertSTBudgetParams struct {
	MonthKey        string `db:"month_key" json:"month_key"`
	CallsUsed       int32  `db:"calls_used" json:"calls_used"`
	DomainsEnriched []byte `db:"domains_enriched" json:"domains_enriched"`
}

func (q *Queries) UpsertSTBudget(ctx context.Context, arg UpsertSTBudgetParams) error {
	_, err := q.db.Exec(ctx, upsertSTBudget, arg.MonthKey, arg.CallsUsed, arg.DomainsEnriched)
	return err
}
