// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: domain_index.sql

package dbq

import (
	"context"
)

const countDomainIndex = `-- name: CountDomainIndex :one
SELECT COUNT(*) FROM domain_index
`

func (q *Queries) CountDomainIndex(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countDomainIndex)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const disablePriorityDomain = `-- name: DisablePriorityDomain :exec
UPDATE priority_domains SET enabled = FALSE WHERE domain = $1
`

func (q *Queries) DisablePriorityDomain(ctx context.Context, domain string) error {
	_, err := q.db.Exec(ctx, disablePriorityDomain, domain)
	return err
}

const getDomainIndexEntry = `-- name: GetDomainIndexEntry :one
SELECT domain, first_seen, last_seen, total_scans, last_score, has_dane, has_dnssec, has_mta_sts, tags FROM domain_index WHERE domain = $1
`

func (q *Queries) GetDomainIndexEntry(ctx context.Context, domain string) (DomainIndex, error) {
	row := q.db.QueryRow(ctx, getDomainIndexEntry, domain)
	var i DomainIndex
	err := row.Scan(
		&i.Domain,
		&i.FirstSeen,
		&i.LastSeen,
		&i.TotalScans,
		&i.LastScore,
		&i.HasDane,
		&i.HasDnssec,
		&i.HasMtaSts,
		&i.Tags,
	)
	return i, err
}

const insertPriorityDomain = `-- name: InsertPriorityDomain :exec
INSERT INTO priority_domains (domain, reason) VALUES ($1, $2)
ON CONFLICT (domain) DO UPDATE SET reason = EXCLUDED.reason, enabled = TRUE
`

type InsertPriorityDomainParams struct {
	Domain string `db:"domain" json:"domain"`
	Reason string `db:"reason" json:"reason"`
}

func (q *Queries) InsertPriorityDomain(ctx context.Context, arg InsertPriorityDomainParams) error {
	_, err := q.db.Exec(ctx, insertPriorityDomain, arg.Domain, arg.Reason)
	return err
}

const listDomainIndexByScans = `-- name: ListDomainIndexByScans :many
SELECT domain, first_seen, last_seen, total_scans, last_score, has_dane, has_dnssec, has_mta_sts, tags
FROM domain_index
ORDER BY total_scans DESC
LIMIT $1
`

func (q *Queries) ListDomainIndexByScans(ctx context.Context, limit int32) ([]DomainIndex, error) {
	rows, err := q.db.Query(ctx, listDomainIndexByScans, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DomainIndex{}
	for rows.Next() {
		var i DomainIndex
		if err := rows.Scan(
			&i.Domain,
			&i.FirstSeen,
			&i.LastSeen,
			&i.TotalScans,
			&i.LastScore,
			&i.HasDane,
			&i.HasDnssec,
			&i.HasMtaSts,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDomainIndexRecent = `-- name: ListDomainIndexRecent :many
SELECT domain, first_seen, last_seen, total_scans, last_score, has_dane, has_dnssec, has_mta_sts, tags
FROM domain_index
ORDER BY last_seen DESC
LIMIT $1
`

func (q *Queries) ListDomainIndexRecent(ctx context.Context, limit int32) ([]DomainIndex, error) {
	rows, err := q.db.Query(ctx, listDomainIndexRecent, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DomainIndex{}
	for rows.Next() {
		var i DomainIndex
		if err := rows.Scan(
			&i.Domain,
			&i.FirstSeen,
			&i.LastSeen,
			&i.TotalScans,
			&i.LastScore,
			&i.HasDane,
			&i.HasDnssec,
			&i.HasMtaSts,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPriorityDomains = `-- name: ListPriorityDomains :many
SELECT domain, reason FROM priority_domains WHERE enabled = TRUE ORDER BY domain
`

type ListPriorityDomainsRow struct {
	Domain string `db:"domain" json:"domain"`
	Reason string `db:"reason" json:"reason"`
}

func (q *Queries) ListPriorityDomains(ctx context.Context) ([]ListPriorityDomainsRow, error) {
	rows, err := q.db.Query(ctx, listPriorityDomains)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPriorityDomainsRow{}
	for rows.Next() {
		var i ListPriorityDomainsRow
		if err := rows.Scan(&i.Domain, &i.Reason); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchDomainIndex = `-- name: SearchDomainIndex :many
SELECT domain, first_seen, last_seen, total_scans, last_score, has_dane, has_dnssec, has_mta_sts, tags
FROM domain_index
WHERE domain ILIKE $1
ORDER BY total_scans DESC
LIMIT $2
`

type SearchDomainIndexParams struct {
	Domain string `db:"domain" json:"domain"`
	Limit  int32  `db:"limit" json:"limit"`
}

func (q *Queries) SearchDomainIndex(ctx context.Context, arg SearchDomainIndexParams) ([]DomainIndex, error) {
	rows, err := q.db.Query(ctx, searchDomainIndex, arg.Domain, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DomainIndex{}
	for rows.Next() {
		var i DomainIndex
		if err := rows.Scan(
			&i.Domain,
			&i.FirstSeen,
			&i.LastSeen,
			&i.TotalScans,
			&i.LastScore,
			&i.HasDane,
			&i.HasDnssec,
			&i.HasMtaSts,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDomainIndex = `-- name: UpsertDomainIndex :exec
INSERT INTO domain_index (domain, first_seen, last_seen, total_scans, last_score, has_dane, has_dnssec, has_mta_sts)
VALUES ($1, NOW(), NOW(), 1, $2, $3, $4, $5)
ON CONFLICT (domain) DO UPDATE SET
    last_seen   = NOW(),
    total_scans = domain_index.total_scans + 1,
    last_score  = EXCLUDED.last_score,
    has_dane    = EXCLUDED.has_dane,
    has_dnssec  = EXCLUDED.has_dnssec,
    has_mta_sts = EXCLUDED.has_mta_sts
`

type UpsertDomainIndexParams struct {
	Domain    string   `db:"domain" json:"domain"`
	LastScore *float32 `db:"last_score" json:"last_score"`
	HasDane   bool     `db:"has_dane" json:"has_dane"`
	HasDnssec bool     `db:"has_dnssec" json:"has_dnssec"`
	HasMtaSts bool     `db:"has_mta_sts" json:"has_mta_sts"`
}

func (q *Queries) UpsertDomainIndex(ctx context.Context, arg UpsertDomainIndexParams) error {
	_, err := q.db.Exec(ctx, upsertDomainIndex,
		arg.Domain,
		arg.LastScore,
		arg.HasDane,
		arg.HasDnssec,
		arg.HasMtaSts,
	)
	return err
}
