// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: drift_events.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countDriftEventsByDomain = `-- name: CountDriftEventsByDomain :one
SELECT COUNT(*) FROM drift_events WHERE domain = $1
`

func (q *Queries) CountDriftEventsByDomain(ctx context.Context, domain string) (int64, error) {
	row := q.db.QueryRow(ctx, countDriftEventsByDomain, domain)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getDriftEvent = `-- name: GetDriftEvent :one
SELECT id, domain, analysis_id, prev_analysis_id, current_hash, previous_hash, diff_summary, severity, created_at FROM drift_events WHERE id = $1
`

func (q *Queries) GetDriftEvent(ctx context.Context, id int32) (DriftEvent, error) {
	row := q.db.QueryRow(ctx, getDriftEvent, id)
	var i DriftEvent
	err := row.Scan(
		&i.ID,
		&i.Domain,
		&i.AnalysisID,
		&i.PrevAnalysisID,
		&i.CurrentHash,
		&i.PreviousHash,
		&i.DiffSummary,
		&i.Severity,
		&i.CreatedAt,
	)
	return i, err
}

const insertDriftEvent = `-- name: InsertDriftEvent :one
INSERT INTO drift_events (domain, analysis_id, prev_analysis_id, current_hash, previous_hash, diff_summary, severity)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, created_at
`

type InsertDriftEventParams struct {
	Domain         string `db:"domain" json:"domain"`
	AnalysisID     int32  `db:"analysis_id" json:"analysis_id"`
	PrevAnalysisID int32  `db:"prev_analysis_id" json:"prev_analysis_id"`
	CurrentHash    string `db:"current_hash" json:"current_hash"`
	PreviousHash   string `db:"previous_hash" json:"previous_hash"`
	DiffSummary    []byte `db:"diff_summary" json:"diff_summary"`
	Severity       string `db:"severity" json:"severity"`
}

type InsertDriftEventRow struct {
	ID        int32            `db:"id" json:"id"`
	CreatedAt pgtype.Timestamp `db:"created_at" json:"created_at"`
}

func (q *Queries) InsertDriftEvent(ctx context.Context, arg InsertDriftEventParams) (InsertDriftEventRow, error) {
	row := q.db.QueryRow(ctx, insertDriftEvent,
		arg.Domain,
		arg.AnalysisID,
		arg.PrevAnalysisID,
		arg.CurrentHash,
		arg.PreviousHash,
		arg.DiffSummary,
		arg.Severity,
	)
	var i InsertDriftEventRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const listDriftEventsByDomain = `-- name: ListDriftEventsByDomain :many
SELECT id, domain, analysis_id, prev_analysis_id, current_hash, previous_hash, diff_summary, severity, created_at
FROM drift_events
WHERE domain = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListDriftEventsByDomainParams struct {
	Domain string `db:"domain" json:"domain"`
	Limit  int32  `db:"limit" json:"limit"`
}

func (q *Queries) ListDriftEventsByDomain(ctx context.Context, arg ListDriftEventsByDomainParams) ([]DriftEvent, error) {
	rows, err := q.db.Query(ctx, listDriftEventsByDomain, arg.Domain, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DriftEvent{}
	for rows.Next() {
		var i DriftEvent
		if err := rows.Scan(
			&i.ID,
			&i.Domain,
			&i.AnalysisID,
			&i.PrevAnalysisID,
			&i.CurrentHash,
			&i.PreviousHash,
			&i.DiffSummary,
			&i.Severity,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentDriftEvents = `-- name: ListRecentDriftEvents :many
SELECT id, domain, analysis_id, prev_analysis_id, current_hash, previous_hash, diff_summary, severity, created_at
FROM drift_events
ORDER BY created_at DESC
LIMIT $1
`

func (q *Queries) ListRecentDriftEvents(ctx context.Context, limit int32) ([]DriftEvent, error) {
	rows, err := q.db.Query(ctx, listRecentDriftEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DriftEvent{}
	for rows.Next() {
		var i DriftEvent
		if err := rows.Scan(
			&i.ID,
			&i.Domain,
			&i.AnalysisID,
			&i.PrevAnalysisID,
			&i.CurrentHash,
			&i.PreviousHash,
			&i.DiffSummary,
			&i.Severity,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
