// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: ede.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countEDEByAttribution = `-- name: CountEDEByAttribution :many
SELECT attribution, COUNT(*) AS count
FROM ede_events
GROUP BY attribution
ORDER BY count DESC
`

type CountEDEByAttributionRow struct {
	Attribution string `db:"attribution" json:"attribution"`
	Count       int64  `db:"count" json:"count"`
}

func (q *Queries) CountEDEByAttribution(ctx context.Context) ([]CountEDEByAttributionRow, error) {
	rows, err := q.db.Query(ctx, countEDEByAttribution)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountEDEByAttributionRow{}
	for rows.Next() {
		var i CountEDEByAttributionRow
		if err := rows.Scan(&i.Attribution, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countEDEByCategory = `-- name: CountEDEByCategory :many
SELECT category, COUNT(*) AS count
FROM ede_events
GROUP BY category
ORDER BY count DESC
`

type CountEDEByCategoryRow struct {
	Category string `db:"category" json:"category"`
	Count    int64  `db:"count" json:"count"`
}

func (q *Queries) CountEDEByCategory(ctx context.Context) ([]CountEDEByCategoryRow, error) {
	rows, err := q.db.Query(ctx, countEDEByCategory)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountEDEByCategoryRow{}
	for rows.Next() {
		var i CountEDEByCategoryRow
		if err := rows.Scan(&i.Category, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countEDEEvents = `-- name: CountEDEEvents :one
SELECT
    COUNT(*) AS total,
    COUNT(*) FILTER (WHERE status = 'open') AS open,
    COUNT(*) FILTER (WHERE status = 'closed') AS closed,
    COUNT(*) FILTER (WHERE category = 'scoring_calibration') AS recalibrations
FROM ede_events
`

type CountEDEEventsRow struct {
	Total          int64 `db:"total" json:"total"`
	Open           int64 `db:"open" json:"open"`
	Closed         int64 `db:"closed" json:"closed"`
	Recalibrations int64 `db:"recalibrations" json:"recalibrations"`
}

func (q *Queries) CountEDEEvents(ctx context.Context) (CountEDEEventsRow, error) {
	row := q.db.QueryRow(ctx, countEDEEvents)
	var i CountEDEEventsRow
	err := row.Scan(
		&i.Total,
		&i.Open,
		&i.Closed,
		&i.Recalibrations,
	)
	return i, err
}

const getEDEEvent = `-- name: GetEDEEvent :one
SELECT id, ede_id, event_date, commit_ref, category, severity, title, status, attribution, protocols_affected, confidence_impact, resolution, bayesian_note, correction_action, prevention_rule, authoritative_source, created_at, updated_at FROM ede_events
WHERE ede_id = $1
`

func (q *Queries) GetEDEEvent(ctx context.Context, edeID string) (EdeEvent, error) {
	row := q.db.QueryRow(ctx, getEDEEvent, edeID)
	var i EdeEvent
	err := row.Scan(
		&i.ID,
		&i.EdeID,
		&i.EventDate,
		&i.CommitRef,
		&i.Category,
		&i.Severity,
		&i.Title,
		&i.Status,
		&i.Attribution,
		&i.ProtocolsAffected,
		&i.ConfidenceImpact,
		&i.Resolution,
		&i.BayesianNote,
		&i.CorrectionAction,
		&i.PreventionRule,
		&i.AuthoritativeSource,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEDEAmendments = `-- name: ListEDEAmendments :many
SELECT a.id, a.ede_event_id, a.amendment_date, a.ground, a.field_changed, a.original_value, a.corrected_to, a.evidence, a.rationale, a.justification, a.created_at, e.ede_id
FROM ede_amendments a
JOIN ede_events e ON e.id = a.ede_event_id
ORDER BY a.amendment_date DESC
`

type ListEDEAmendmentsRow struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	EdeEventID    pgtype.UUID        `db:"ede_event_id" json:"ede_event_id"`
	AmendmentDate pgtype.Date        `db:"amendment_date" json:"amendment_date"`
	Ground        string             `db:"ground" json:"ground"`
	FieldChanged  string             `db:"field_changed" json:"field_changed"`
	OriginalValue string             `db:"original_value" json:"original_value"`
	CorrectedTo   string             `db:"corrected_to" json:"corrected_to"`
	Evidence      *string            `db:"evidence" json:"evidence"`
	Rationale     *string            `db:"rationale" json:"rationale"`
	Justification string             `db:"justification" json:"justification"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	EdeID         string             `db:"ede_id" json:"ede_id"`
}

func (q *Queries) ListEDEAmendments(ctx context.Context) ([]ListEDEAmendmentsRow, error) {
	rows, err := q.db.Query(ctx, listEDEAmendments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEDEAmendmentsRow{}
	for rows.Next() {
		var i ListEDEAmendmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.EdeEventID,
			&i.AmendmentDate,
			&i.Ground,
			&i.FieldChanged,
			&i.OriginalValue,
			&i.CorrectedTo,
			&i.Evidence,
			&i.Rationale,
			&i.Justification,
			&i.CreatedAt,
			&i.EdeID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEDEAmendmentsByEvent = `-- name: ListEDEAmendmentsByEvent :many
SELECT id, ede_event_id, amendment_date, ground, field_changed, original_value, corrected_to, evidence, rationale, justification, created_at FROM ede_amendments
WHERE ede_event_id = $1
ORDER BY amendment_date
`

func (q *Queries) ListEDEAmendmentsByEvent(ctx context.Context, edeEventID pgtype.UUID) ([]EdeAmendment, error) {
	rows, err := q.db.Query(ctx, listEDEAmendmentsByEvent, edeEventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EdeAmendment{}
	for rows.Next() {
		var i EdeAmendment
		if err := rows.Scan(
			&i.ID,
			&i.EdeEventID,
			&i.AmendmentDate,
			&i.Ground,
			&i.FieldChanged,
			&i.OriginalValue,
			&i.CorrectedTo,
			&i.Evidence,
			&i.Rationale,
			&i.Justification,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEDEEvents = `-- name: ListEDEEvents :many
SELECT id, ede_id, event_date, commit_ref, category, severity, title, status, attribution, protocols_affected, confidence_impact, resolution, bayesian_note, correction_action, prevention_rule, authoritative_source, created_at, updated_at FROM ede_events
ORDER BY event_date DESC
`

func (q *Queries) ListEDEEvents(ctx context.Context) ([]EdeEvent, error) {
	rows, err := q.db.Query(ctx, listEDEEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EdeEvent{}
	for rows.Next() {
		var i EdeEvent
		if err := rows.Scan(
			&i.ID,
			&i.EdeID,
			&i.EventDate,
			&i.CommitRef,
			&i.Category,
			&i.Severity,
			&i.Title,
			&i.Status,
			&i.Attribution,
			&i.ProtocolsAffected,
			&i.ConfidenceImpact,
			&i.Resolution,
			&i.BayesianNote,
			&i.CorrectionAction,
			&i.PreventionRule,
			&i.AuthoritativeSource,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEDEEventsByAttribution = `-- name: ListEDEEventsByAttribution :many
SELECT id, ede_id, event_date, commit_ref, category, severity, title, status, attribution, protocols_affected, confidence_impact, resolution, bayesian_note, correction_action, prevention_rule, authoritative_source, created_at, updated_at FROM ede_events
WHERE attribution = $1
ORDER BY event_date DESC
`

func (q *Queries) ListEDEEventsByAttribution(ctx context.Context, attribution string) ([]EdeEvent, error) {
	rows, err := q.db.Query(ctx, listEDEEventsByAttribution, attribution)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EdeEvent{}
	for rows.Next() {
		var i EdeEvent
		if err := rows.Scan(
			&i.ID,
			&i.EdeID,
			&i.EventDate,
			&i.CommitRef,
			&i.Category,
			&i.Severity,
			&i.Title,
			&i.Status,
			&i.Attribution,
			&i.ProtocolsAffected,
			&i.ConfidenceImpact,
			&i.Resolution,
			&i.BayesianNote,
			&i.CorrectionAction,
			&i.PreventionRule,
			&i.AuthoritativeSource,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEDEEventsByCategory = `-- name: ListEDEEventsByCategory :many
SELECT id, ede_id, event_date, commit_ref, category, severity, title, status, attribution, protocols_affected, confidence_impact, resolution, bayesian_note, correction_action, prevention_rule, authoritative_source, created_at, updated_at FROM ede_events
WHERE category = $1
ORDER BY event_date DESC
`

func (q *Queries) ListEDEEventsByCategory(ctx context.Context, category string) ([]EdeEvent, error) {
	rows, err := q.db.Query(ctx, listEDEEventsByCategory, category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EdeEvent{}
	for rows.Next() {
		var i EdeEvent
		if err := rows.Scan(
			&i.ID,
			&i.EdeID,
			&i.EventDate,
			&i.CommitRef,
			&i.Category,
			&i.Severity,
			&i.Title,
			&i.Status,
			&i.Attribution,
			&i.ProtocolsAffected,
			&i.ConfidenceImpact,
			&i.Resolution,
			&i.BayesianNote,
			&i.CorrectionAction,
			&i.PreventionRule,
			&i.AuthoritativeSource,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEDEEventsBySeverity = `-- name: ListEDEEventsBySeverity :many
SELECT id, ede_id, event_date, commit_ref, category, severity, title, status, attribution, protocols_affected, confidence_impact, resolution, bayesian_note, correction_action, prevention_rule, authoritative_source, created_at, updated_at FROM ede_events
WHERE severity = $1
ORDER BY event_date DESC
`

func (q *Queries) ListEDEEventsBySeverity(ctx context.Context, severity string) ([]EdeEvent, error) {
	rows, err := q.db.Query(ctx, listEDEEventsBySeverity, severity)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EdeEvent{}
	for rows.Next() {
		var i EdeEvent
		if err := rows.Scan(
			&i.ID,
			&i.EdeID,
			&i.EventDate,
			&i.CommitRef,
			&i.Category,
			&i.Severity,
			&i.Title,
			&i.Status,
			&i.Attribution,
			&i.ProtocolsAffected,
			&i.ConfidenceImpact,
			&i.Resolution,
			&i.BayesianNote,
			&i.CorrectionAction,
			&i.PreventionRule,
			&i.AuthoritativeSource,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
