// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: findings.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countFindingsByDomain = `-- name: CountFindingsByDomain :many
SELECT domain, COUNT(*) as count
FROM findings
GROUP BY domain
ORDER BY domain
`

type CountFindingsByDomainRow struct {
	Domain string `db:"domain" json:"domain"`
	Count  int64  `db:"count" json:"count"`
}

func (q *Queries) CountFindingsByDomain(ctx context.Context) ([]CountFindingsByDomainRow, error) {
	rows, err := q.db.Query(ctx, countFindingsByDomain)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountFindingsByDomainRow{}
	for rows.Next() {
		var i CountFindingsByDomainRow
		if err := rows.Scan(&i.Domain, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countFindingsByKind = `-- name: CountFindingsByKind :many
SELECT kind, COUNT(*) as count
FROM findings
GROUP BY kind
ORDER BY kind
`

type CountFindingsByKindRow struct {
	Kind  string `db:"kind" json:"kind"`
	Count int64  `db:"count" json:"count"`
}

func (q *Queries) CountFindingsByKind(ctx context.Context) ([]CountFindingsByKindRow, error) {
	rows, err := q.db.Query(ctx, countFindingsByKind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountFindingsByKindRow{}
	for rows.Next() {
		var i CountFindingsByKindRow
		if err := rows.Scan(&i.Kind, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countFindingsBySeverity = `-- name: CountFindingsBySeverity :many
SELECT severity, COUNT(*) as count
FROM findings
GROUP BY severity
ORDER BY severity
`

type CountFindingsBySeverityRow struct {
	Severity int16 `db:"severity" json:"severity"`
	Count    int64 `db:"count" json:"count"`
}

func (q *Queries) CountFindingsBySeverity(ctx context.Context) ([]CountFindingsBySeverityRow, error) {
	rows, err := q.db.Query(ctx, countFindingsBySeverity)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountFindingsBySeverityRow{}
	for rows.Next() {
		var i CountFindingsBySeverityRow
		if err := rows.Scan(&i.Severity, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countFindingsByStatus = `-- name: CountFindingsByStatus :many
SELECT status, COUNT(*) as count
FROM findings
GROUP BY status
ORDER BY status
`

type CountFindingsByStatusRow struct {
	Status string `db:"status" json:"status"`
	Count  int64  `db:"count" json:"count"`
}

func (q *Queries) CountFindingsByStatus(ctx context.Context) ([]CountFindingsByStatusRow, error) {
	rows, err := q.db.Query(ctx, countFindingsByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountFindingsByStatusRow{}
	for rows.Next() {
		var i CountFindingsByStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countFindingsTotal = `-- name: CountFindingsTotal :one
SELECT COUNT(*) as count FROM findings
`

func (q *Queries) CountFindingsTotal(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countFindingsTotal)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createFinding = `-- name: CreateFinding :one
INSERT INTO findings (
    public_id, kind, domain, title, symptom_md, hypothesis_md, root_cause_md,
    severity, priority, status, canonical_rule_id, fingerprint_version,
    fingerprint_sha256, evidence_grade, confidence, blast_radius, visibility,
    standard_refs, source_team, owner, introduced_commit, legacy_bsi_id, legacy_threat_level
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23
) RETURNING id, public_id, kind, domain, title, symptom_md, hypothesis_md, root_cause_md, severity, priority, status, canonical_rule_id, fingerprint_version, fingerprint_sha256, evidence_grade, confidence, blast_radius, visibility, standard_refs, duplicate_of, regression_of, source_team, owner, introduced_commit, fixed_commit, fixed_release, legacy_bsi_id, legacy_threat_level, created_at, updated_at
`

type CreateFindingParams struct {
	PublicID           string         `db:"public_id" json:"public_id"`
	Kind               string         `db:"kind" json:"kind"`
	Domain             string         `db:"domain" json:"domain"`
	Title              string         `db:"title" json:"title"`
	SymptomMd          string         `db:"symptom_md" json:"symptom_md"`
	HypothesisMd       *string        `db:"hypothesis_md" json:"hypothesis_md"`
	RootCauseMd        *string        `db:"root_cause_md" json:"root_cause_md"`
	Severity           int16          `db:"severity" json:"severity"`
	Priority           int16          `db:"priority" json:"priority"`
	Status             string         `db:"status" json:"status"`
	CanonicalRuleID    string         `db:"canonical_rule_id" json:"canonical_rule_id"`
	FingerprintVersion int16          `db:"fingerprint_version" json:"fingerprint_version"`
	FingerprintSha256  string         `db:"fingerprint_sha256" json:"fingerprint_sha256"`
	EvidenceGrade      string         `db:"evidence_grade" json:"evidence_grade"`
	Confidence         pgtype.Numeric `db:"confidence" json:"confidence"`
	BlastRadius        string         `db:"blast_radius" json:"blast_radius"`
	Visibility         string         `db:"visibility" json:"visibility"`
	StandardRefs       []byte         `db:"standard_refs" json:"standard_refs"`
	SourceTeam         string         `db:"source_team" json:"source_team"`
	Owner              *string        `db:"owner" json:"owner"`
	IntroducedCommit   *string        `db:"introduced_commit" json:"introduced_commit"`
	LegacyBsiID        *string        `db:"legacy_bsi_id" json:"legacy_bsi_id"`
	LegacyThreatLevel  *string        `db:"legacy_threat_level" json:"legacy_threat_level"`
}

func (q *Queries) CreateFinding(ctx context.Context, arg CreateFindingParams) (Finding, error) {
	row := q.db.QueryRow(ctx, createFinding,
		arg.PublicID,
		arg.Kind,
		arg.Domain,
		arg.Title,
		arg.SymptomMd,
		arg.HypothesisMd,
		arg.RootCauseMd,
		arg.Severity,
		arg.Priority,
		arg.Status,
		arg.CanonicalRuleID,
		arg.FingerprintVersion,
		arg.FingerprintSha256,
		arg.EvidenceGrade,
		arg.Confidence,
		arg.BlastRadius,
		arg.Visibility,
		arg.StandardRefs,
		arg.SourceTeam,
		arg.Owner,
		arg.IntroducedCommit,
		arg.LegacyBsiID,
		arg.LegacyThreatLevel,
	)
	var i Finding
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Kind,
		&i.Domain,
		&i.Title,
		&i.SymptomMd,
		&i.HypothesisMd,
		&i.RootCauseMd,
		&i.Severity,
		&i.Priority,
		&i.Status,
		&i.CanonicalRuleID,
		&i.FingerprintVersion,
		&i.FingerprintSha256,
		&i.EvidenceGrade,
		&i.Confidence,
		&i.BlastRadius,
		&i.Visibility,
		&i.StandardRefs,
		&i.DuplicateOf,
		&i.RegressionOf,
		&i.SourceTeam,
		&i.Owner,
		&i.IntroducedCommit,
		&i.FixedCommit,
		&i.FixedRelease,
		&i.LegacyBsiID,
		&i.LegacyThreatLevel,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createFindingEvent = `-- name: CreateFindingEvent :one
INSERT INTO finding_events (
    finding_id, actor, event_type, from_status, to_status, commit_sha, note_md
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, finding_id, actor, event_type, from_status, to_status, commit_sha, note_md, created_at
`

type CreateFindingEventParams struct {
	FindingID  pgtype.UUID `db:"finding_id" json:"finding_id"`
	Actor      string      `db:"actor" json:"actor"`
	EventType  string      `db:"event_type" json:"event_type"`
	FromStatus *string     `db:"from_status" json:"from_status"`
	ToStatus   *string     `db:"to_status" json:"to_status"`
	CommitSha  *string     `db:"commit_sha" json:"commit_sha"`
	NoteMd     *string     `db:"note_md" json:"note_md"`
}

func (q *Queries) CreateFindingEvent(ctx context.Context, arg CreateFindingEventParams) (FindingEvent, error) {
	row := q.db.QueryRow(ctx, createFindingEvent,
		arg.FindingID,
		arg.Actor,
		arg.EventType,
		arg.FromStatus,
		arg.ToStatus,
		arg.CommitSha,
		arg.NoteMd,
	)
	var i FindingEvent
	err := row.Scan(
		&i.ID,
		&i.FindingID,
		&i.Actor,
		&i.EventType,
		&i.FromStatus,
		&i.ToStatus,
		&i.CommitSha,
		&i.NoteMd,
		&i.CreatedAt,
	)
	return i, err
}

const createObservation = `-- name: CreateObservation :one
INSERT INTO observations (
    finding_id, source_team, build_id, route, component,
    browser, viewport, repro_steps_md, evidence_sha256, raw_evidence
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
) RETURNING id, finding_id, source_team, build_id, route, component, browser, viewport, repro_steps_md, evidence_sha256, raw_evidence, observed_at
`

type CreateObservationParams struct {
	FindingID      pgtype.UUID `db:"finding_id" json:"finding_id"`
	SourceTeam     string      `db:"source_team" json:"source_team"`
	BuildID        *string     `db:"build_id" json:"build_id"`
	Route          *string     `db:"route" json:"route"`
	Component      *string     `db:"component" json:"component"`
	Browser        *string     `db:"browser" json:"browser"`
	Viewport       *string     `db:"viewport" json:"viewport"`
	ReproStepsMd   *string     `db:"repro_steps_md" json:"repro_steps_md"`
	EvidenceSha256 string      `db:"evidence_sha256" json:"evidence_sha256"`
	RawEvidence    []byte      `db:"raw_evidence" json:"raw_evidence"`
}

func (q *Queries) CreateObservation(ctx context.Context, arg CreateObservationParams) (Observation, error) {
	row := q.db.QueryRow(ctx, createObservation,
		arg.FindingID,
		arg.SourceTeam,
		arg.BuildID,
		arg.Route,
		arg.Component,
		arg.Browser,
		arg.Viewport,
		arg.ReproStepsMd,
		arg.EvidenceSha256,
		arg.RawEvidence,
	)
	var i Observation
	err := row.Scan(
		&i.ID,
		&i.FindingID,
		&i.SourceTeam,
		&i.BuildID,
		&i.Route,
		&i.Component,
		&i.Browser,
		&i.Viewport,
		&i.ReproStepsMd,
		&i.EvidenceSha256,
		&i.RawEvidence,
		&i.ObservedAt,
	)
	return i, err
}

const getFinding = `-- name: GetFinding :one
SELECT id, public_id, kind, domain, title, symptom_md, hypothesis_md, root_cause_md, severity, priority, status, canonical_rule_id, fingerprint_version, fingerprint_sha256, evidence_grade, confidence, blast_radius, visibility, standard_refs, duplicate_of, regression_of, source_team, owner, introduced_commit, fixed_commit, fixed_release, legacy_bsi_id, legacy_threat_level, created_at, updated_at FROM findings
WHERE public_id = $1
`

func (q *Queries) GetFinding(ctx context.Context, publicID string) (Finding, error) {
	row := q.db.QueryRow(ctx, getFinding, publicID)
	var i Finding
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Kind,
		&i.Domain,
		&i.Title,
		&i.SymptomMd,
		&i.HypothesisMd,
		&i.RootCauseMd,
		&i.Severity,
		&i.Priority,
		&i.Status,
		&i.CanonicalRuleID,
		&i.FingerprintVersion,
		&i.FingerprintSha256,
		&i.EvidenceGrade,
		&i.Confidence,
		&i.BlastRadius,
		&i.Visibility,
		&i.StandardRefs,
		&i.DuplicateOf,
		&i.RegressionOf,
		&i.SourceTeam,
		&i.Owner,
		&i.IntroducedCommit,
		&i.FixedCommit,
		&i.FixedRelease,
		&i.LegacyBsiID,
		&i.LegacyThreatLevel,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFindingByID = `-- name: GetFindingByID :one
SELECT id, public_id, kind, domain, title, symptom_md, hypothesis_md, root_cause_md, severity, priority, status, canonical_rule_id, fingerprint_version, fingerprint_sha256, evidence_grade, confidence, blast_radius, visibility, standard_refs, duplicate_of, regression_of, source_team, owner, introduced_commit, fixed_commit, fixed_release, legacy_bsi_id, legacy_threat_level, created_at, updated_at FROM findings
WHERE id = $1
`

func (q *Queries) GetFindingByID(ctx context.Context, id pgtype.UUID) (Finding, error) {
	row := q.db.QueryRow(ctx, getFindingByID, id)
	var i Finding
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Kind,
		&i.Domain,
		&i.Title,
		&i.SymptomMd,
		&i.HypothesisMd,
		&i.RootCauseMd,
		&i.Severity,
		&i.Priority,
		&i.Status,
		&i.CanonicalRuleID,
		&i.FingerprintVersion,
		&i.FingerprintSha256,
		&i.EvidenceGrade,
		&i.Confidence,
		&i.BlastRadius,
		&i.Visibility,
		&i.StandardRefs,
		&i.DuplicateOf,
		&i.RegressionOf,
		&i.SourceTeam,
		&i.Owner,
		&i.IntroducedCommit,
		&i.FixedCommit,
		&i.FixedRelease,
		&i.LegacyBsiID,
		&i.LegacyThreatLevel,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFindingEvents = `-- name: ListFindingEvents :many
SELECT fe.id, fe.finding_id, fe.actor, fe.event_type, fe.from_status, fe.to_status, fe.commit_sha, fe.note_md, fe.created_at, f.public_id, f.title, f.severity
FROM finding_events fe
JOIN findings f ON f.id = fe.finding_id
ORDER BY fe.created_at DESC
`

type ListFindingEventsRow struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	FindingID  pgtype.UUID        `db:"finding_id" json:"finding_id"`
	Actor      string             `db:"actor" json:"actor"`
	EventType  string             `db:"event_type" json:"event_type"`
	FromStatus *string            `db:"from_status" json:"from_status"`
	ToStatus   *string            `db:"to_status" json:"to_status"`
	CommitSha  *string            `db:"commit_sha" json:"commit_sha"`
	NoteMd     *string            `db:"note_md" json:"note_md"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	PublicID   string             `db:"public_id" json:"public_id"`
	Title      string             `db:"title" json:"title"`
	Severity   int16              `db:"severity" json:"severity"`
}

func (q *Queries) ListFindingEvents(ctx context.Context) ([]ListFindingEventsRow, error) {
	rows, err := q.db.Query(ctx, listFindingEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFindingEventsRow{}
	for rows.Next() {
		var i ListFindingEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.FindingID,
			&i.Actor,
			&i.EventType,
			&i.FromStatus,
			&i.ToStatus,
			&i.CommitSha,
			&i.NoteMd,
			&i.CreatedAt,
			&i.PublicID,
			&i.Title,
			&i.Severity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFindingEventsForFinding = `-- name: ListFindingEventsForFinding :many
SELECT id, finding_id, actor, event_type, from_status, to_status, commit_sha, note_md, created_at FROM finding_events
WHERE finding_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListFindingEventsForFinding(ctx context.Context, findingID pgtype.UUID) ([]FindingEvent, error) {
	rows, err := q.db.Query(ctx, listFindingEventsForFinding, findingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindingEvent{}
	for rows.Next() {
		var i FindingEvent
		if err := rows.Scan(
			&i.ID,
			&i.FindingID,
			&i.Actor,
			&i.EventType,
			&i.FromStatus,
			&i.ToStatus,
			&i.CommitSha,
			&i.NoteMd,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFindings = `-- name: ListFindings :many
SELECT id, public_id, kind, domain, title, symptom_md, hypothesis_md, root_cause_md, severity, priority, status, canonical_rule_id, fingerprint_version, fingerprint_sha256, evidence_grade, confidence, blast_radius, visibility, standard_refs, duplicate_of, regression_of, source_team, owner, introduced_commit, fixed_commit, fixed_release, legacy_bsi_id, legacy_threat_level, created_at, updated_at FROM findings
ORDER BY severity, priority, public_id
`

func (q *Queries) ListFindings(ctx context.Context) ([]Finding, error) {
	rows, err := q.db.Query(ctx, listFindings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Finding{}
	for rows.Next() {
		var i Finding
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.Kind,
			&i.Domain,
			&i.Title,
			&i.SymptomMd,
			&i.HypothesisMd,
			&i.RootCauseMd,
			&i.Severity,
			&i.Priority,
			&i.Status,
			&i.CanonicalRuleID,
			&i.FingerprintVersion,
			&i.FingerprintSha256,
			&i.EvidenceGrade,
			&i.Confidence,
			&i.BlastRadius,
			&i.Visibility,
			&i.StandardRefs,
			&i.DuplicateOf,
			&i.RegressionOf,
			&i.SourceTeam,
			&i.Owner,
			&i.IntroducedCommit,
			&i.FixedCommit,
			&i.FixedRelease,
			&i.LegacyBsiID,
			&i.LegacyThreatLevel,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFindingsByDomain = `-- name: ListFindingsByDomain :many
SELECT id, public_id, kind, domain, title, symptom_md, hypothesis_md, root_cause_md, severity, priority, status, canonical_rule_id, fingerprint_version, fingerprint_sha256, evidence_grade, confidence, blast_radius, visibility, standard_refs, duplicate_of, regression_of, source_team, owner, introduced_commit, fixed_commit, fixed_release, legacy_bsi_id, legacy_threat_level, created_at, updated_at FROM findings
WHERE domain = $1
ORDER BY severity, priority, public_id
`

func (q *Queries) ListFindingsByDomain(ctx context.Context, domain string) ([]Finding, error) {
	rows, err := q.db.Query(ctx, listFindingsByDomain, domain)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Finding{}
	for rows.Next() {
		var i Finding
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.Kind,
			&i.Domain,
			&i.Title,
			&i.SymptomMd,
			&i.HypothesisMd,
			&i.RootCauseMd,
			&i.Severity,
			&i.Priority,
			&i.Status,
			&i.CanonicalRuleID,
			&i.FingerprintVersion,
			&i.FingerprintSha256,
			&i.EvidenceGrade,
			&i.Confidence,
			&i.BlastRadius,
			&i.Visibility,
			&i.StandardRefs,
			&i.DuplicateOf,
			&i.RegressionOf,
			&i.SourceTeam,
			&i.Owner,
			&i.IntroducedCommit,
			&i.FixedCommit,
			&i.FixedRelease,
			&i.LegacyBsiID,
			&i.LegacyThreatLevel,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFindingsByKind = `-- name: ListFindingsByKind :many
SELECT id, public_id, kind, domain, title, symptom_md, hypothesis_md, root_cause_md, severity, priority, status, canonical_rule_id, fingerprint_version, fingerprint_sha256, evidence_grade, confidence, blast_radius, visibility, standard_refs, duplicate_of, regression_of, source_team, owner, introduced_commit, fixed_commit, fixed_release, legacy_bsi_id, legacy_threat_level, created_at, updated_at FROM findings
WHERE kind = $1
ORDER BY severity, priority, public_id
`

func (q *Queries) ListFindingsByKind(ctx context.Context, kind string) ([]Finding, error) {
	rows, err := q.db.Query(ctx, listFindingsByKind, kind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Finding{}
	for rows.Next() {
		var i Finding
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.Kind,
			&i.Domain,
			&i.Title,
			&i.SymptomMd,
			&i.HypothesisMd,
			&i.RootCauseMd,
			&i.Severity,
			&i.Priority,
			&i.Status,
			&i.CanonicalRuleID,
			&i.FingerprintVersion,
			&i.FingerprintSha256,
			&i.EvidenceGrade,
			&i.Confidence,
			&i.BlastRadius,
			&i.Visibility,
			&i.StandardRefs,
			&i.DuplicateOf,
			&i.RegressionOf,
			&i.SourceTeam,
			&i.Owner,
			&i.IntroducedCommit,
			&i.FixedCommit,
			&i.FixedRelease,
			&i.LegacyBsiID,
			&i.LegacyThreatLevel,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFindingsBySeverity = `-- name: ListFindingsBySeverity :many
SELECT id, public_id, kind, domain, title, symptom_md, hypothesis_md, root_cause_md, severity, priority, status, canonical_rule_id, fingerprint_version, fingerprint_sha256, evidence_grade, confidence, blast_radius, visibility, standard_refs, duplicate_of, regression_of, source_team, owner, introduced_commit, fixed_commit, fixed_release, legacy_bsi_id, legacy_threat_level, created_at, updated_at FROM findings
WHERE severity = $1
ORDER BY priority, public_id
`

func (q *Queries) ListFindingsBySeverity(ctx context.Context, severity int16) ([]Finding, error) {
	rows, err := q.db.Query(ctx, listFindingsBySeverity, severity)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Finding{}
	for rows.Next() {
		var i Finding
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.Kind,
			&i.Domain,
			&i.Title,
			&i.SymptomMd,
			&i.HypothesisMd,
			&i.RootCauseMd,
			&i.Severity,
			&i.Priority,
			&i.Status,
			&i.CanonicalRuleID,
			&i.FingerprintVersion,
			&i.FingerprintSha256,
			&i.EvidenceGrade,
			&i.Confidence,
			&i.BlastRadius,
			&i.Visibility,
			&i.StandardRefs,
			&i.DuplicateOf,
			&i.RegressionOf,
			&i.SourceTeam,
			&i.Owner,
			&i.IntroducedCommit,
			&i.FixedCommit,
			&i.FixedRelease,
			&i.LegacyBsiID,
			&i.LegacyThreatLevel,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFindingsByStatus = `-- name: ListFindingsByStatus :many
SELECT id, public_id, kind, domain, title, symptom_md, hypothesis_md, root_cause_md, severity, priority, status, canonical_rule_id, fingerprint_version, fingerprint_sha256, evidence_grade, confidence, blast_radius, visibility, standard_refs, duplicate_of, regression_of, source_team, owner, introduced_commit, fixed_commit, fixed_release, legacy_bsi_id, legacy_threat_level, created_at, updated_at FROM findings
WHERE status = $1
ORDER BY severity, priority, public_id
`

func (q *Queries) ListFindingsByStatus(ctx context.Context, status string) ([]Finding, error) {
	rows, err := q.db.Query(ctx, listFindingsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Finding{}
	for rows.Next() {
		var i Finding
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.Kind,
			&i.Domain,
			&i.Title,
			&i.SymptomMd,
			&i.HypothesisMd,
			&i.RootCauseMd,
			&i.Severity,
			&i.Priority,
			&i.Status,
			&i.CanonicalRuleID,
			&i.FingerprintVersion,
			&i.FingerprintSha256,
			&i.EvidenceGrade,
			&i.Confidence,
			&i.BlastRadius,
			&i.Visibility,
			&i.StandardRefs,
			&i.DuplicateOf,
			&i.RegressionOf,
			&i.SourceTeam,
			&i.Owner,
			&i.IntroducedCommit,
			&i.FixedCommit,
			&i.FixedRelease,
			&i.LegacyBsiID,
			&i.LegacyThreatLevel,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listObservationsForFinding = `-- name: ListObservationsForFinding :many
SELECT id, finding_id, source_team, build_id, route, component, browser, viewport, repro_steps_md, evidence_sha256, raw_evidence, observed_at FROM observations
WHERE finding_id = $1
ORDER BY observed_at DESC
`

func (q *Queries) ListObservationsForFinding(ctx context.Context, findingID pgtype.UUID) ([]Observation, error) {
	rows, err := q.db.Query(ctx, listObservationsForFinding, findingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Observation{}
	for rows.Next() {
		var i Observation
		if err := rows.Scan(
			&i.ID,
			&i.FindingID,
			&i.SourceTeam,
			&i.BuildID,
			&i.Route,
			&i.Component,
			&i.Browser,
			&i.Viewport,
			&i.ReproStepsMd,
			&i.EvidenceSha256,
			&i.RawEvidence,
			&i.ObservedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFindingFix = `-- name: UpdateFindingFix :exec
UPDATE findings
SET status = 'RENDERED', fixed_commit = $2, fixed_release = $3, root_cause_md = $4, updated_at = NOW()
WHERE public_id = $1
`

type UpdateFindingFixParams struct {
	PublicID     string  `db:"public_id" json:"public_id"`
	FixedCommit  *string `db:"fixed_commit" json:"fixed_commit"`
	FixedRelease *string `db:"fixed_release" json:"fixed_release"`
	RootCauseMd  *string `db:"root_cause_md" json:"root_cause_md"`
}

func (q *Queries) UpdateFindingFix(ctx context.Context, arg UpdateFindingFixParams) error {
	_, err := q.db.Exec(ctx, updateFindingFix,
		arg.PublicID,
		arg.FixedCommit,
		arg.FixedRelease,
		arg.RootCauseMd,
	)
	return err
}

const updateFindingStatus = `-- name: UpdateFindingStatus :exec
UPDATE findings
SET status = $2, updated_at = NOW()
WHERE public_id = $1
`

type UpdateFindingStatusParams struct {
	PublicID string `db:"public_id" json:"public_id"`
	Status   string `db:"status" json:"status"`
}

func (q *Queries) UpdateFindingStatus(ctx context.Context, arg UpdateFindingStatusParams) error {
	_, err := q.db.Exec(ctx, updateFindingStatus, arg.PublicID, arg.Status)
	return err
}
