// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: icuae.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const iCuAEGetAggregateStats = `-- name: ICuAEGetAggregateStats :one
SELECT
    COUNT(*)::integer AS total_scans,
    COALESCE(AVG(overall_score), 0)::real AS avg_score,
    COALESCE(STDDEV_POP(overall_score), 0)::real AS stddev_score,
    MAX(created_at) AS last_evaluated_at
FROM icuae_scan_scores
`

type ICuAEGetAggregateStatsRow struct {
	TotalScans      int32       `db:"total_scans" json:"total_scans"`
	AvgScore        float32     `db:"avg_score" json:"avg_score"`
	StddevScore     float32     `db:"stddev_score" json:"stddev_score"`
	LastEvaluatedAt interface{} `db:"last_evaluated_at" json:"last_evaluated_at"`
}

func (q *Queries) ICuAEGetAggregateStats(ctx context.Context) (ICuAEGetAggregateStatsRow, error) {
	row := q.db.QueryRow(ctx, iCuAEGetAggregateStats)
	var i ICuAEGetAggregateStatsRow
	err := row.Scan(
		&i.TotalScans,
		&i.AvgScore,
		&i.StddevScore,
		&i.LastEvaluatedAt,
	)
	return i, err
}

const iCuAEGetDimensionAverages = `-- name: ICuAEGetDimensionAverages :many
SELECT
    dimension,
    COALESCE(AVG(score), 0)::real AS avg_score,
    COALESCE(STDDEV_POP(score), 0)::real AS stddev_score,
    COUNT(*)::integer AS sample_count
FROM icuae_dimension_scores
GROUP BY dimension
ORDER BY dimension ASC
`

type ICuAEGetDimensionAveragesRow struct {
	Dimension   string  `db:"dimension" json:"dimension"`
	AvgScore    float32 `db:"avg_score" json:"avg_score"`
	StddevScore float32 `db:"stddev_score" json:"stddev_score"`
	SampleCount int32   `db:"sample_count" json:"sample_count"`
}

func (q *Queries) ICuAEGetDimensionAverages(ctx context.Context) ([]ICuAEGetDimensionAveragesRow, error) {
	rows, err := q.db.Query(ctx, iCuAEGetDimensionAverages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ICuAEGetDimensionAveragesRow{}
	for rows.Next() {
		var i ICuAEGetDimensionAveragesRow
		if err := rows.Scan(
			&i.Dimension,
			&i.AvgScore,
			&i.StddevScore,
			&i.SampleCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const iCuAEGetGradeDistribution = `-- name: ICuAEGetGradeDistribution :many
SELECT
    overall_grade AS grade,
    COUNT(*)::integer AS count
FROM icuae_scan_scores
GROUP BY overall_grade
ORDER BY overall_grade ASC
`

type ICuAEGetGradeDistributionRow struct {
	Grade string `db:"grade" json:"grade"`
	Count int32  `db:"count" json:"count"`
}

func (q *Queries) ICuAEGetGradeDistribution(ctx context.Context) ([]ICuAEGetGradeDistributionRow, error) {
	rows, err := q.db.Query(ctx, iCuAEGetGradeDistribution)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ICuAEGetGradeDistributionRow{}
	for rows.Next() {
		var i ICuAEGetGradeDistributionRow
		if err := rows.Scan(&i.Grade, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const iCuAEGetRecentTrend = `-- name: ICuAEGetRecentTrend :many
SELECT
    overall_score,
    created_at
FROM icuae_scan_scores
ORDER BY created_at DESC
LIMIT $1
`

type ICuAEGetRecentTrendRow struct {
	OverallScore float32          `db:"overall_score" json:"overall_score"`
	CreatedAt    pgtype.Timestamp `db:"created_at" json:"created_at"`
}

func (q *Queries) ICuAEGetRecentTrend(ctx context.Context, limit int32) ([]ICuAEGetRecentTrendRow, error) {
	rows, err := q.db.Query(ctx, iCuAEGetRecentTrend, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ICuAEGetRecentTrendRow{}
	for rows.Next() {
		var i ICuAEGetRecentTrendRow
		if err := rows.Scan(&i.OverallScore, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const iCuAEInsertDimensionScore = `-- name: ICuAEInsertDimensionScore :exec
INSERT INTO icuae_dimension_scores (scan_id, dimension, score, grade, record_types_evaluated, record_types_list)
VALUES ($1, $2, $3, $4, $5, $6)
`

type ICuAEInsertDimensionScoreParams struct {
	ScanID               int32    `db:"scan_id" json:"scan_id"`
	Dimension            string   `db:"dimension" json:"dimension"`
	Score                float32  `db:"score" json:"score"`
	Grade                string   `db:"grade" json:"grade"`
	RecordTypesEvaluated int32    `db:"record_types_evaluated" json:"record_types_evaluated"`
	RecordTypesList      []string `db:"record_types_list" json:"record_types_list"`
}

func (q *Queries) ICuAEInsertDimensionScore(ctx context.Context, arg ICuAEInsertDimensionScoreParams) error {
	_, err := q.db.Exec(ctx, iCuAEInsertDimensionScore,
		arg.ScanID,
		arg.Dimension,
		arg.Score,
		arg.Grade,
		arg.RecordTypesEvaluated,
		arg.RecordTypesList,
	)
	return err
}

const iCuAEInsertScanScore = `-- name: ICuAEInsertScanScore :one
INSERT INTO icuae_scan_scores (domain, overall_score, overall_grade, resolver_count, record_count, app_version)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, created_at
`

type ICuAEInsertScanScoreParams struct {
	Domain        string  `db:"domain" json:"domain"`
	OverallScore  float32 `db:"overall_score" json:"overall_score"`
	OverallGrade  string  `db:"overall_grade" json:"overall_grade"`
	ResolverCount int32   `db:"resolver_count" json:"resolver_count"`
	RecordCount   int32   `db:"record_count" json:"record_count"`
	AppVersion    string  `db:"app_version" json:"app_version"`
}

type ICuAEInsertScanScoreRow struct {
	ID        int32            `db:"id" json:"id"`
	CreatedAt pgtype.Timestamp `db:"created_at" json:"created_at"`
}

func (q *Queries) ICuAEInsertScanScore(ctx context.Context, arg ICuAEInsertScanScoreParams) (ICuAEInsertScanScoreRow, error) {
	row := q.db.QueryRow(ctx, iCuAEInsertScanScore,
		arg.Domain,
		arg.OverallScore,
		arg.OverallGrade,
		arg.ResolverCount,
		arg.RecordCount,
		arg.AppVersion,
	)
	var i ICuAEInsertScanScoreRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}
