// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: scan_telemetry.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDriftSeverityDistribution = `-- name: GetDriftSeverityDistribution :many
SELECT severity, COUNT(*) AS count
FROM drift_events
WHERE created_at >= NOW() - INTERVAL '30 days'
GROUP BY severity
ORDER BY count DESC
`

type GetDriftSeverityDistributionRow struct {
	Severity string `db:"severity" json:"severity"`
	Count    int64  `db:"count" json:"count"`
}

func (q *Queries) GetDriftSeverityDistribution(ctx context.Context) ([]GetDriftSeverityDistributionRow, error) {
	rows, err := q.db.Query(ctx, getDriftSeverityDistribution)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDriftSeverityDistributionRow{}
	for rows.Next() {
		var i GetDriftSeverityDistributionRow
		if err := rows.Scan(&i.Severity, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPipelineDurationDistribution = `-- name: GetPipelineDurationDistribution :many
SELECT
    CASE
        WHEN total_duration_ms < 2000 THEN '0-2s'
        WHEN total_duration_ms < 5000 THEN '2-5s'
        WHEN total_duration_ms < 10000 THEN '5-10s'
        WHEN total_duration_ms < 20000 THEN '10-20s'
        WHEN total_duration_ms < 30000 THEN '20-30s'
        WHEN total_duration_ms < 60000 THEN '30-60s'
        ELSE '60s+'
    END AS bucket,
    COUNT(*) AS count
FROM scan_telemetry_hash
WHERE created_at >= NOW() - INTERVAL '30 days'
GROUP BY bucket
ORDER BY MIN(total_duration_ms)
`

type GetPipelineDurationDistributionRow struct {
	Bucket string `db:"bucket" json:"bucket"`
	Count  int64  `db:"count" json:"count"`
}

func (q *Queries) GetPipelineDurationDistribution(ctx context.Context) ([]GetPipelineDurationDistributionRow, error) {
	rows, err := q.db.Query(ctx, getPipelineDurationDistribution)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPipelineDurationDistributionRow{}
	for rows.Next() {
		var i GetPipelineDurationDistributionRow
		if err := rows.Scan(&i.Bucket, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPipelineEndToEndStats = `-- name: GetPipelineEndToEndStats :one
SELECT COUNT(*) AS total_scans,
       AVG(total_duration_ms)::INT AS avg_total_ms,
       PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY total_duration_ms)::INT AS p50_total_ms,
       PERCENTILE_CONT(0.95) WITHIN GROUP (ORDER BY total_duration_ms)::INT AS p95_total_ms,
       PERCENTILE_CONT(0.99) WITHIN GROUP (ORDER BY total_duration_ms)::INT AS p99_total_ms,
       MIN(total_duration_ms) AS min_total_ms,
       MAX(total_duration_ms) AS max_total_ms
FROM scan_telemetry_hash
WHERE created_at >= NOW() - INTERVAL '30 days'
`

type GetPipelineEndToEndStatsRow struct {
	TotalScans int64       `db:"total_scans" json:"total_scans"`
	AvgTotalMs int32       `db:"avg_total_ms" json:"avg_total_ms"`
	P50TotalMs int32       `db:"p50_total_ms" json:"p50_total_ms"`
	P95TotalMs int32       `db:"p95_total_ms" json:"p95_total_ms"`
	P99TotalMs int32       `db:"p99_total_ms" json:"p99_total_ms"`
	MinTotalMs interface{} `db:"min_total_ms" json:"min_total_ms"`
	MaxTotalMs interface{} `db:"max_total_ms" json:"max_total_ms"`
}

func (q *Queries) GetPipelineEndToEndStats(ctx context.Context) (GetPipelineEndToEndStatsRow, error) {
	row := q.db.QueryRow(ctx, getPipelineEndToEndStats)
	var i GetPipelineEndToEndStatsRow
	err := row.Scan(
		&i.TotalScans,
		&i.AvgTotalMs,
		&i.P50TotalMs,
		&i.P95TotalMs,
		&i.P99TotalMs,
		&i.MinTotalMs,
		&i.MaxTotalMs,
	)
	return i, err
}

const getPipelineStageStats = `-- name: GetPipelineStageStats :many
SELECT phase_group,
       COUNT(DISTINCT analysis_id) AS scan_count,
       AVG(duration_ms)::INT AS avg_ms,
       PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY duration_ms)::INT AS p50_ms,
       PERCENTILE_CONT(0.95) WITHIN GROUP (ORDER BY duration_ms)::INT AS p95_ms,
       PERCENTILE_CONT(0.99) WITHIN GROUP (ORDER BY duration_ms)::INT AS p99_ms,
       MIN(duration_ms) AS min_ms,
       MAX(duration_ms) AS max_ms,
       SUM(record_count)::BIGINT AS total_records,
       SUM(CASE WHEN error <> '' THEN 1 ELSE 0 END)::INT AS error_count
FROM scan_phase_telemetry
WHERE created_at >= NOW() - INTERVAL '30 days'
GROUP BY phase_group
ORDER BY AVG(started_at_ms)
`

type GetPipelineStageStatsRow struct {
	PhaseGroup   string      `db:"phase_group" json:"phase_group"`
	ScanCount    int64       `db:"scan_count" json:"scan_count"`
	AvgMs        int32       `db:"avg_ms" json:"avg_ms"`
	P50Ms        int32       `db:"p50_ms" json:"p50_ms"`
	P95Ms        int32       `db:"p95_ms" json:"p95_ms"`
	P99Ms        int32       `db:"p99_ms" json:"p99_ms"`
	MinMs        interface{} `db:"min_ms" json:"min_ms"`
	MaxMs        interface{} `db:"max_ms" json:"max_ms"`
	TotalRecords int64       `db:"total_records" json:"total_records"`
	ErrorCount   int32       `db:"error_count" json:"error_count"`
}

func (q *Queries) GetPipelineStageStats(ctx context.Context) ([]GetPipelineStageStatsRow, error) {
	rows, err := q.db.Query(ctx, getPipelineStageStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPipelineStageStatsRow{}
	for rows.Next() {
		var i GetPipelineStageStatsRow
		if err := rows.Scan(
			&i.PhaseGroup,
			&i.ScanCount,
			&i.AvgMs,
			&i.P50Ms,
			&i.P95Ms,
			&i.P99Ms,
			&i.MinMs,
			&i.MaxMs,
			&i.TotalRecords,
			&i.ErrorCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentTelemetrySummaries = `-- name: GetRecentTelemetrySummaries :many
SELECT sth.analysis_id, da.ascii_domain, sth.total_duration_ms, sth.phase_count, sth.sha3_512, sth.created_at
FROM scan_telemetry_hash sth
JOIN domain_analyses da ON da.id = sth.analysis_id
ORDER BY sth.created_at DESC
LIMIT $1
`

type GetRecentTelemetrySummariesRow struct {
	AnalysisID      int32            `db:"analysis_id" json:"analysis_id"`
	AsciiDomain     string           `db:"ascii_domain" json:"ascii_domain"`
	TotalDurationMs int32            `db:"total_duration_ms" json:"total_duration_ms"`
	PhaseCount      int32            `db:"phase_count" json:"phase_count"`
	Sha3512         string           `db:"sha3_512" json:"sha3_512"`
	CreatedAt       pgtype.Timestamp `db:"created_at" json:"created_at"`
}

func (q *Queries) GetRecentTelemetrySummaries(ctx context.Context, limit int32) ([]GetRecentTelemetrySummariesRow, error) {
	rows, err := q.db.Query(ctx, getRecentTelemetrySummaries, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRecentTelemetrySummariesRow{}
	for rows.Next() {
		var i GetRecentTelemetrySummariesRow
		if err := rows.Scan(
			&i.AnalysisID,
			&i.AsciiDomain,
			&i.TotalDurationMs,
			&i.PhaseCount,
			&i.Sha3512,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSlowestPhases = `-- name: GetSlowestPhases :many
SELECT phase_group, phase_task, AVG(duration_ms)::INT AS avg_ms,
       PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY duration_ms)::INT AS p50_ms,
       PERCENTILE_CONT(0.95) WITHIN GROUP (ORDER BY duration_ms)::INT AS p95_ms,
       PERCENTILE_CONT(0.99) WITHIN GROUP (ORDER BY duration_ms)::INT AS p99_ms,
       COUNT(*) AS sample_count
FROM scan_phase_telemetry
WHERE created_at >= NOW() - INTERVAL '7 days'
GROUP BY phase_group, phase_task
ORDER BY p95_ms DESC
LIMIT $1
`

type GetSlowestPhasesRow struct {
	PhaseGroup  string `db:"phase_group" json:"phase_group"`
	PhaseTask   string `db:"phase_task" json:"phase_task"`
	AvgMs       int32  `db:"avg_ms" json:"avg_ms"`
	P50Ms       int32  `db:"p50_ms" json:"p50_ms"`
	P95Ms       int32  `db:"p95_ms" json:"p95_ms"`
	P99Ms       int32  `db:"p99_ms" json:"p99_ms"`
	SampleCount int64  `db:"sample_count" json:"sample_count"`
}

func (q *Queries) GetSlowestPhases(ctx context.Context, limit int32) ([]GetSlowestPhasesRow, error) {
	rows, err := q.db.Query(ctx, getSlowestPhases, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSlowestPhasesRow{}
	for rows.Next() {
		var i GetSlowestPhasesRow
		if err := rows.Scan(
			&i.PhaseGroup,
			&i.PhaseTask,
			&i.AvgMs,
			&i.P50Ms,
			&i.P95Ms,
			&i.P99Ms,
			&i.SampleCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTelemetryByAnalysis = `-- name: GetTelemetryByAnalysis :many
SELECT id, analysis_id, phase_group, phase_task, started_at_ms, duration_ms, record_count, error, created_at
FROM scan_phase_telemetry
WHERE analysis_id = $1
ORDER BY started_at_ms, phase_task
`

func (q *Queries) GetTelemetryByAnalysis(ctx context.Context, analysisID int32) ([]ScanPhaseTelemetry, error) {
	rows, err := q.db.Query(ctx, getTelemetryByAnalysis, analysisID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScanPhaseTelemetry{}
	for rows.Next() {
		var i ScanPhaseTelemetry
		if err := rows.Scan(
			&i.ID,
			&i.AnalysisID,
			&i.PhaseGroup,
			&i.PhaseTask,
			&i.StartedAtMs,
			&i.DurationMs,
			&i.RecordCount,
			&i.Error,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTelemetryHash = `-- name: GetTelemetryHash :one
SELECT analysis_id, total_duration_ms, phase_count, sha3_512, created_at
FROM scan_telemetry_hash
WHERE analysis_id = $1
`

func (q *Queries) GetTelemetryHash(ctx context.Context, analysisID int32) (ScanTelemetryHash, error) {
	row := q.db.QueryRow(ctx, getTelemetryHash, analysisID)
	var i ScanTelemetryHash
	err := row.Scan(
		&i.AnalysisID,
		&i.TotalDurationMs,
		&i.PhaseCount,
		&i.Sha3512,
		&i.CreatedAt,
	)
	return i, err
}

const getTelemetryTrends = `-- name: GetTelemetryTrends :many
SELECT spt.phase_group,
       DATE(spt.created_at) AS trend_date,
       AVG(spt.duration_ms)::INT AS avg_duration_ms,
       COUNT(*) AS sample_count
FROM scan_phase_telemetry spt
WHERE spt.created_at >= NOW() - INTERVAL '7 days'
GROUP BY spt.phase_group, DATE(spt.created_at)
ORDER BY trend_date, spt.phase_group
`

type GetTelemetryTrendsRow struct {
	PhaseGroup    string      `db:"phase_group" json:"phase_group"`
	TrendDate     pgtype.Date `db:"trend_date" json:"trend_date"`
	AvgDurationMs int32       `db:"avg_duration_ms" json:"avg_duration_ms"`
	SampleCount   int64       `db:"sample_count" json:"sample_count"`
}

func (q *Queries) GetTelemetryTrends(ctx context.Context) ([]GetTelemetryTrendsRow, error) {
	rows, err := q.db.Query(ctx, getTelemetryTrends)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTelemetryTrendsRow{}
	for rows.Next() {
		var i GetTelemetryTrendsRow
		if err := rows.Scan(
			&i.PhaseGroup,
			&i.TrendDate,
			&i.AvgDurationMs,
			&i.SampleCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertPhaseTelemetry = `-- name: InsertPhaseTelemetry :exec
INSERT INTO scan_phase_telemetry (analysis_id, phase_group, phase_task, started_at_ms, duration_ms, record_count, error)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertPhaseTelemetryParams struct {
	AnalysisID  int32   `db:"analysis_id" json:"analysis_id"`
	PhaseGroup  string  `db:"phase_group" json:"phase_group"`
	PhaseTask   string  `db:"phase_task" json:"phase_task"`
	StartedAtMs int32   `db:"started_at_ms" json:"started_at_ms"`
	DurationMs  int32   `db:"duration_ms" json:"duration_ms"`
	RecordCount *int32  `db:"record_count" json:"record_count"`
	Error       *string `db:"error" json:"error"`
}

func (q *Queries) InsertPhaseTelemetry(ctx context.Context, arg InsertPhaseTelemetryParams) error {
	_, err := q.db.Exec(ctx, insertPhaseTelemetry,
		arg.AnalysisID,
		arg.PhaseGroup,
		arg.PhaseTask,
		arg.StartedAtMs,
		arg.DurationMs,
		arg.RecordCount,
		arg.Error,
	)
	return err
}

const insertTelemetryHash = `-- name: InsertTelemetryHash :exec
INSERT INTO scan_telemetry_hash (analysis_id, total_duration_ms, phase_count, sha3_512)
VALUES ($1, $2, $3, $4)
`

type InsertTelemetryHashParams struct {
	AnalysisID      int32  `db:"analysis_id" json:"analysis_id"`
	TotalDurationMs int32  `db:"total_duration_ms" json:"total_duration_ms"`
	PhaseCount      int32  `db:"phase_count" json:"phase_count"`
	Sha3512         string `db:"sha3_512" json:"sha3_512"`
}

func (q *Queries) InsertTelemetryHash(ctx context.Context, arg InsertTelemetryHashParams) error {
	_, err := q.db.Exec(ctx, insertTelemetryHash,
		arg.AnalysisID,
		arg.TotalDurationMs,
		arg.PhaseCount,
		arg.Sha3512,
	)
	return err
}
