// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: system_logs.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countSystemLogs = `-- name: CountSystemLogs :one
SELECT count(*) FROM system_log_entries
`

func (q *Queries) CountSystemLogs(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countSystemLogs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getLogLevelCounts = `-- name: GetLogLevelCounts :many
SELECT level, count(*) as cnt
FROM system_log_entries
WHERE timestamp > NOW() - INTERVAL '24 hours'
GROUP BY level
ORDER BY cnt DESC
`

type GetLogLevelCountsRow struct {
	Level string `db:"level" json:"level"`
	Cnt   int64  `db:"cnt" json:"cnt"`
}

func (q *Queries) GetLogLevelCounts(ctx context.Context) ([]GetLogLevelCountsRow, error) {
	rows, err := q.db.Query(ctx, getLogLevelCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetLogLevelCountsRow{}
	for rows.Next() {
		var i GetLogLevelCountsRow
		if err := rows.Scan(&i.Level, &i.Cnt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentLogEvents = `-- name: GetRecentLogEvents :many
SELECT event, count(*) as cnt
FROM system_log_entries
WHERE timestamp > NOW() - INTERVAL '24 hours'
  AND event != ''
GROUP BY event
ORDER BY cnt DESC
LIMIT 20
`

type GetRecentLogEventsRow struct {
	Event string `db:"event" json:"event"`
	Cnt   int64  `db:"cnt" json:"cnt"`
}

func (q *Queries) GetRecentLogEvents(ctx context.Context) ([]GetRecentLogEventsRow, error) {
	rows, err := q.db.Query(ctx, getRecentLogEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRecentLogEventsRow{}
	for rows.Next() {
		var i GetRecentLogEventsRow
		if err := rows.Scan(&i.Event, &i.Cnt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSystemLogs = `-- name: ListSystemLogs :many
SELECT id, timestamp, level, message, event, category, domain, trace_id, attrs
FROM system_log_entries
WHERE
    ($1::text IS NULL OR level = $1)
    AND ($2::text IS NULL OR category = $2)
    AND ($3::text IS NULL OR domain ILIKE '%' || $3 || '%')
    AND ($4::text IS NULL OR trace_id = $4)
    AND ($5::timestamp IS NULL OR timestamp >= $5)
    AND ($6::timestamp IS NULL OR timestamp <= $6)
ORDER BY timestamp DESC
LIMIT $7
`

type ListSystemLogsParams struct {
	Level         *string          `db:"level" json:"level"`
	Category      *string          `db:"category" json:"category"`
	DomainFilter  *string          `db:"domain_filter" json:"domain_filter"`
	TraceIDFilter *string          `db:"trace_id_filter" json:"trace_id_filter"`
	AfterTs       pgtype.Timestamp `db:"after_ts" json:"after_ts"`
	BeforeTs      pgtype.Timestamp `db:"before_ts" json:"before_ts"`
	MaxRows       int32            `db:"max_rows" json:"max_rows"`
}

type ListSystemLogsRow struct {
	ID        int32            `db:"id" json:"id"`
	Timestamp pgtype.Timestamp `db:"timestamp" json:"timestamp"`
	Level     string           `db:"level" json:"level"`
	Message   string           `db:"message" json:"message"`
	Event     string           `db:"event" json:"event"`
	Category  string           `db:"category" json:"category"`
	Domain    string           `db:"domain" json:"domain"`
	TraceID   string           `db:"trace_id" json:"trace_id"`
	Attrs     []byte           `db:"attrs" json:"attrs"`
}

func (q *Queries) ListSystemLogs(ctx context.Context, arg ListSystemLogsParams) ([]ListSystemLogsRow, error) {
	rows, err := q.db.Query(ctx, listSystemLogs,
		arg.Level,
		arg.Category,
		arg.DomainFilter,
		arg.TraceIDFilter,
		arg.AfterTs,
		arg.BeforeTs,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSystemLogsRow{}
	for rows.Next() {
		var i ListSystemLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.Timestamp,
			&i.Level,
			&i.Message,
			&i.Event,
			&i.Category,
			&i.Domain,
			&i.TraceID,
			&i.Attrs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneSystemLogs = `-- name: PruneSystemLogs :exec
DELETE FROM system_log_entries
WHERE id NOT IN (
    SELECT id FROM system_log_entries
    ORDER BY timestamp DESC
    LIMIT $1
)
`

func (q *Queries) PruneSystemLogs(ctx context.Context, limit int32) error {
	_, err := q.db.Exec(ctx, pruneSystemLogs, limit)
	return err
}
