// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: zone_imports.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertZoneImport = `-- name: InsertZoneImport :one
INSERT INTO zone_imports (user_id, domain, sha256_hash, original_filename, file_size, record_count, retained, zone_data, drift_summary)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, created_at
`

type InsertZoneImportParams struct {
	UserID           int32   `db:"user_id" json:"user_id"`
	Domain           string  `db:"domain" json:"domain"`
	Sha256Hash       string  `db:"sha256_hash" json:"sha256_hash"`
	OriginalFilename string  `db:"original_filename" json:"original_filename"`
	FileSize         int32   `db:"file_size" json:"file_size"`
	RecordCount      int32   `db:"record_count" json:"record_count"`
	Retained         bool    `db:"retained" json:"retained"`
	ZoneData         *string `db:"zone_data" json:"zone_data"`
	DriftSummary     []byte  `db:"drift_summary" json:"drift_summary"`
}

type InsertZoneImportRow struct {
	ID        int32            `db:"id" json:"id"`
	CreatedAt pgtype.Timestamp `db:"created_at" json:"created_at"`
}

func (q *Queries) InsertZoneImport(ctx context.Context, arg InsertZoneImportParams) (InsertZoneImportRow, error) {
	row := q.db.QueryRow(ctx, insertZoneImport,
		arg.UserID,
		arg.Domain,
		arg.Sha256Hash,
		arg.OriginalFilename,
		arg.FileSize,
		arg.RecordCount,
		arg.Retained,
		arg.ZoneData,
		arg.DriftSummary,
	)
	var i InsertZoneImportRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const listUserZoneImports = `-- name: ListUserZoneImports :many
SELECT id, domain, sha256_hash, original_filename, file_size, record_count, retained, created_at
FROM zone_imports
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListUserZoneImportsParams struct {
	UserID int32 `db:"user_id" json:"user_id"`
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

type ListUserZoneImportsRow struct {
	ID               int32            `db:"id" json:"id"`
	Domain           string           `db:"domain" json:"domain"`
	Sha256Hash       string           `db:"sha256_hash" json:"sha256_hash"`
	OriginalFilename string           `db:"original_filename" json:"original_filename"`
	FileSize         int32            `db:"file_size" json:"file_size"`
	RecordCount      int32            `db:"record_count" json:"record_count"`
	Retained         bool             `db:"retained" json:"retained"`
	CreatedAt        pgtype.Timestamp `db:"created_at" json:"created_at"`
}

func (q *Queries) ListUserZoneImports(ctx context.Context, arg ListUserZoneImportsParams) ([]ListUserZoneImportsRow, error) {
	rows, err := q.db.Query(ctx, listUserZoneImports, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserZoneImportsRow{}
	for rows.Next() {
		var i ListUserZoneImportsRow
		if err := rows.Scan(
			&i.ID,
			&i.Domain,
			&i.Sha256Hash,
			&i.OriginalFilename,
			&i.FileSize,
			&i.RecordCount,
			&i.Retained,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
