-- Migration 001: Data Governance Events table + pre-v26.19.0 data purge
-- Applied: 2026-02-15
-- Operator: admin
-- Status: EXECUTED (one-time operational migration)
--
-- Context: Pre-v26.19.0 analyses contained findings generated by code with known
-- limitations (DKIM selector discovery, provider pattern matching). Reports carry
-- SHA-256 integrity hashes, making silent correction impossible. No external
-- retention promises existed at time of purge.
--
-- After this migration, analysis data is IMMUTABLE and APPEND-ONLY.
-- No further deletions or mutations without formal governance review.

-- Step 1: Create audit log table
CREATE TABLE IF NOT EXISTS data_governance_events (
    id SERIAL PRIMARY KEY,
    event_type VARCHAR(50) NOT NULL,
    description TEXT NOT NULL,
    scope TEXT,
    affected_count INTEGER,
    reason TEXT NOT NULL,
    operator VARCHAR(100) NOT NULL DEFAULT 'system',
    metadata JSONB,
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- Step 2: Log the purge event (executed before deletion)
-- Audit event ID 1: 317 analyses purged (42 version strings, Feb 8-15 2026)
-- Audit event ID 2: 3 analysis_stats rows cleared (aggregates from purged data)

-- Step 3: Purge pre-v26.19.0 analyses
-- DELETE FROM domain_analyses
-- WHERE full_results->>'_tool_version' IS NULL
--    OR full_results->>'_tool_version' < '26.19.0';
-- Result: DELETE 317

-- Step 4: Clear stale stats
-- DELETE FROM analysis_stats;
-- Result: DELETE 3

-- Verification: SELECT COUNT(*) FROM domain_analyses; → 2 (both v26.19.0)
-- Verification: SELECT * FROM data_governance_events; → 2 audit records
