name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
      - name: Build site
        run: mkdocs build -f docs/mkdocs.yml

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2

