name: Release

on:
  push:
    tags: ["v*"]

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            target: linux-amd64-glibc
            ext: ""
          - os: ubuntu-22.04
            target: linux-arm64-glibc
            ext: ""
          - os: macos-14
            target: macos-silicon
            ext: ""
          - os: macos-13
            target: macos-intel
            ext: ""
          - os: windows-2022
            target: windows-amd64
            ext: ".exe"

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: python -m pip install --upgrade pip pyinstaller -r requirements.txt

      - name: Build binary
        run: pyinstaller --onefile dnstool.py --clean

      - name: Rename artefact
        run: |
          mv dist/dnstool${{ matrix.ext }} \
             dnstool-${{ matrix.target }}-${{ github.ref_name }}${{ matrix.ext }}
        shell: bash

      - uses: softprops/action-gh-release@v2
        with:
          files: dnstool-${{ matrix.target }}-${{ github.ref_name }}${{ matrix.ext }}
          generate_release_notes: true
